baseURL = "https://manuellington.github.io/ux-ui-design-portfolio/"
languageCode = "en-us"
title = "Manuel Ferro UX/UI Designer"
theme = "hugo-resume"
publishDir = "docs"

[params]
    firstName = "Manuel"
    lastName = "Ferro"
    address = "Miami, FL"
    phone = "305.613.9689"
    contactNote = "UX/UI Designer"
    profileImage = "img/TechChat.png"
    email = "maferro55@gmail.com"
    description = " "
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
